### ISSUE TITLE
Microsoft Vision API Keys found in source

### ISSUE THREAD

**Issue by johnbindel** [penglu20/Bigbang#4]
https://github.com/l465659833/Bigbang/blob/1f55712d0c9e141387995cf35555d4077fffb7a0/app/src/main/java/com/forfan/bigbang/util/OcrAnalsyser.java

Since these keys are checked into the public github, anyone can see/use them. You should probably get new keys, retire these and store these with non-version-controlled config.

**Comment by shang1101** [comment]
Thanks for your advice.
